# Generated by Django 5.0.7 on 2024-10-13 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.street'),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(related_name='business_category', to='business.category'),
        ),
        migrations.AddField(
            model_name='mybusiness',
            name='associated_businesses',
            field=models.ManyToManyField(related_name='associated_users', to='business.business'),
        ),
        migrations.AddField(
            model_name='mybusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_businesses', to='business.business'),
        ),
        migrations.AddField(
            model_name='mybusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
